export { FeatureCard } from "./feature-card";
export { AdvantageCard } from "./advantage-card";
export { SectionTitle } from "./section-title";
export { TrialStep } from "./trial-step";
export { HeroSection } from "./hero-section";
export { FeaturesSection } from "./features-section";
export { AdvantagesSection } from "./advantages-section";
export { AIBusinessSection } from "./ai-business-section";
export { TrialProcessSection } from "./trial-process-section";
export { CTASection } from "./cta-section";
export { featureCards, advantageCards, trialSteps } from "./data";
export type { FeatureData, AdvantageData, TrialStepData } from "./data";
