import type { DataType } from "./types";

export const comparisonData: DataType[] = [
  {
    key: "1",
    title: "搜索引导页面组件",
    tengence: true,
    algolia: true,
    row: 1,
    categoryId: "standardPageComp",
  },
  {
    key: "2",
    title: "搜索结果页面组件",
    tengence: true,
    algolia: true,
    row: 1,
    categoryId: "standardPageComp",
  },
  {
    key: "3",
    title: "行为数据",
    type: "自助采集",
    tengence: true,
    algolia: true,
    ali: true,
    row: 2,
    categoryId: "standardPageComp",
  },
  {
    key: "4",
    title: "行为数据",
    type: "自动采集",
    tengence: true,
    algolia: true,
    row: 0,
    categoryId: "standardPageComp",
  },
  {
    key: "5",
    title: "效果预览",
    tengence: true,
    algolia: true,
    unbxd: true,
    row: 1,
    categoryId: "standardPageComp",
  },
  {
    key: "6",
    title: "下拉提示",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "searchGuidance",
  },
  {
    key: "7",
    title: "下拉提示",
    type: "自助训练模型",
    tengence: true,
    algolia: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "8",
    title: "下拉提示",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "9",
    title: "热词",
    type: "内置模型",
    tengence: true,
    ali: true,
    row: 3,
    categoryId: "searchGuidance",
  },
  {
    key: "10",
    title: "热词",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "11",
    title: "热词",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "12",
    title: "底纹词",
    type: "内置模型",
    tengence: true,
    ali: true,
    row: 3,
    categoryId: "searchGuidance",
  },
  {
    key: "13",
    title: "底纹词",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "14",
    title: "底纹词",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "15",
    title: "历史词",
    type: "标准实现",
    tengence: true,
    row: 1,
    categoryId: "searchGuidance",
  },
  {
    key: "16",
    title: "相关搜索",
    type: "内置模型",
    tengence: true,
    row: 3,
    categoryId: "searchGuidance",
  },
  {
    key: "17",
    title: "相关搜索",
    type: "自助训练模型",
    tengence: true,
    ali: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "18",
    title: "相关搜索",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "searchGuidance",
  },
  {
    key: "19",
    title: "标准化",
    type: "标准实现",
    tengence: true,
    algolia: true,
    ali: true,
    row: 1,
    categoryId: "intent",
  },
  {
    key: "20",
    title: "分词",
    type: "内置模型",
    tengence: true,
    ali: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "21",
    title: "分词",
    type: "自助训练模型",
    tengence: true,
    ali: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "22",
    title: "分词",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "23",
    title: "停用词",
    type: "标准实现",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 1,
    categoryId: "intent",
  },
  {
    key: "24",
    title: "纠错",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "25",
    title: "纠错",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "26",
    title: "纠错",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "27",
    title: "同义词",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "28",
    title: "同义词",
    type: "自助训练模型",
    tengence: true,
    algolia: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "29",
    title: "同义词",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "30",
    title: "命名实体识别",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "31",
    title: "命名实体识别",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "32",
    title: "命名实体识别",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "33",
    title: "类目预测",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "34",
    title: "类目预测",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "35",
    title: "类目预测",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "36",
    title: "词权重",
    type: "内置模型",
    tengence: true,
    ali: true,
    row: 3,
    categoryId: "intent",
  },
  {
    key: "37",
    title: "词权重",
    type: "自助训练模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "38",
    title: "词权重",
    type: "定制模型",
    tengence: true,
    row: 0,
    categoryId: "intent",
  },
  {
    key: "42",
    title: "倒排召回",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    aws: true,
    elastic: true,
    row: 1,
    categoryId: "recall",
  },
  {
    key: "43",
    title: "多路召回",
    tengence: true,
    ali: true,
    row: 1,
    categoryId: "recall",
  },
  {
    key: "44",
    title: "AI语义召回",
    tengence: true,
    ali: true,
    aws: true,
    elastic: true,
    row: 1,
    categoryId: "recall",
  },
  {
    key: "45",
    title: "粗排公式",
    tengence: true,
    ali: true,
    aws: true,
    elastic: true,
    row: 1,
    categoryId: "sort",
  },
  {
    key: "46",
    title: "粗排模型",
    type: "内置模型",
    tengence: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "sort",
  },
  {
    key: "47",
    title: "粗排模型",
    type: "自助训练模型",
    tengence: true,
    ali: true,
    row: 0,
    categoryId: "sort",
  },
  {
    key: "48",
    title: "粗排模型",
    type: "定制粗排模型",
    tengence: true,
    row: 0,
    categoryId: "sort",
  },
  {
    key: "49",
    title: "精排公式",
    tengence: true,
    ali: true,
    aws: true,
    elastic: true,
    row: 1,
    categoryId: "sort",
  },
  {
    key: "50",
    title: "精排模型",
    type: "内置模型",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 3,
    categoryId: "sort",
  },
  {
    key: "51",
    title: "精排模型",
    type: "自助训练模型",
    tengence: true,
    algolia: true,
    ali: true,
    row: 0,
    categoryId: "sort",
  },
  {
    key: "52",
    title: "精排模型",
    type: "定制精排模型",
    tengence: true,
    row: 0,
    categoryId: "sort",
  },
  {
    key: "53",
    title: "插入固定位置",
    tengence: true,
    algolia: true,
    unbxd: true,
    row: 1,
    categoryId: "intervention",
  },
  {
    key: "54",
    title: "按条件屏蔽",
    tengence: true,
    algolia: true,
    row: 1,
    categoryId: "intervention",
  },
  {
    key: "55",
    title: "搜索直达",
    tengence: true,
    algolia: true,
    unbxd: true,
    row: 1,
    categoryId: "intervention",
  },
  {
    key: "56",
    title: "结果打散",
    tengence: true,
    algolia: true,
    row: 1,
    categoryId: "intervention",
  },
  {
    key: "57",
    title: "排序加权",
    tengence: true,
    algolia: true,
    row: 1,
    categoryId: "intervention",
  },
  {
    key: "58",
    title: "数据源同步",
    tengence: true,
    algolia: true,
    ali: true,
    row: 1,
    categoryId: "dataCollect",
  },
  {
    key: "59",
    title: "实时数据推送",
    tengence: true,
    row: 1,
    categoryId: "dataCollect",
  },
  {
    key: "60",
    title: "标准报表",
    tengence: true,
    algolia: true,
    ali: true,
    unbxd: true,
    row: 1,
    categoryId: "reportForms",
  },
  {
    key: "61",
    title: "无少结果报表",
    tengence: true,
    algolia: true,
    unbxd: true,
    row: 1,
    categoryId: "reportForms",
  },
  {
    key: "62",
    title: "慢查询报表",
    tengence: true,
    ali: true,
    aws: true,
    elastic: true,
    row: 1,
    categoryId: "reportForms",
  },
  {
    key: "63",
    title: "引导成交报表",
    tengence: true,
    row: 1,
    categoryId: "reportForms",
  },
  {
    key: "64",
    title: "AB测试报表",
    tengence: true,
    algolia: true,
    unbxd: true,
    row: 1,
    categoryId: "reportForms",
  },
  {
    key: "65",
    title: "自助服务",
    type: "自助调试",
    tengence: true,
    algolia: true,
    ali: true,
    aws: true,
    row: 3,
    categoryId: "server",
  },
  {
    key: "66",
    title: "自助服务",
    type: "诊断报告",
    tengence: true,
    row: 0,
    categoryId: "server",
  },
  {
    key: "67",
    title: "自助服务",
    type: "智能客服",
    tengence: true,
    ali: true,
    aws: true,
    row: 0,
    categoryId: "server",
  },
  {
    key: "68",
    title: "专家服务",
    type: "问题诊断",
    tengence: true,
    ali: true,
    aws: true,
    row: 3,
    categoryId: "server",
  },
  {
    key: "69",
    title: "专家服务",
    type: "效果调优",
    tengence: true,
    ali: true,
    aws: true,
    row: 0,
    categoryId: "server",
  },
  {
    key: "70",
    title: "专家服务",
    type: "性能调优",
    tengence: true,
    ali: true,
    aws: true,
    row: 0,
    categoryId: "server",
  },
  {
    key: "71",
    title: "专属服务",
    type: "专属客户经理",
    tengence: true,
    ali: true,
    aws: true,
    row: 2,
    categoryId: "server",
  },
  {
    key: "72",
    title: "专属服务",
    type: "专属服务群",
    tengence: true,
    ali: true,
    row: 0,
    categoryId: "server",
  },
  {
    key: "73",
    title: "定制开发",
    tengence: true,
    elastic: true,
    row: 1,
    categoryId: "server",
  },
  {
    key: "74",
    title: "私有化部署",
    tengence: true,
    elastic: true,
    row: 1,
    categoryId: "server",
  },
  {
    key: "75",
    title: "项目制合作",
    tengence: true,
    row: 1,
    categoryId: "server",
  },
];
