name: Deploy Trigger

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Deployment
        run: |
          echo '{"event_type":"deploy-web-prod","client_payload":{"repository":"${{ github.repository }}","ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}' | gh api --method POST repos/tengence-team/tengence-deployment/dispatches --input -
        env:
          GH_TOKEN: ${{ github.token }}
