name: Deploy Trigger

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/tengence-team/tengence-deployment/dispatches \
            -d '{"event_type":"deploy-web-prod","client_payload":{"repository":"${{ github.repository }}","ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
