name: Deploy Trigger (Production)

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  trigger-deployment:
    name: Trigger Production Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Deployment
        run: |
          gh api \
            --method POST \
            /repos/tengence-team/tengence-deployment/dispatches \
            -f event_type=deploy-web-prod \
            -f client_payload[repository]=${{ github.repository }} \
            -f client_payload[ref]=${{ github.ref }} \
            -f client_payload[sha]=${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
