name: Deploy Trigger

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Production Deployment
        run: |
          gh repo set-default tengence-team/tengence-deployment
          cat <<EOF | gh api --method POST repos/tengence-team/tengence-deployment/dispatches --input -
          {
            "event_type": "deploy-web-prod",
            "client_payload": {
              "repository": "tengence-team/tengence-website",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }
          }
          EOF
        env:
          GH_TOKEN: ${{ github.token }}
